apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    k8c.io/operating-system-profile: osp-flatcar-cloud-init
  name: anexia-machinedeployment
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: anexia-machinedeployment
  template:
    metadata:
      labels:
        name: anexia-machinedeployment
    spec:
      providerSpec:
        value:
          cloudProvider: anexia
          cloudProviderSpec:
            # from 1 to 16 cores
            cpus: 4

            # anything supported by the Anexia Engine
            cpuPerformanceType: performance

            # from 1024 to 65536 MB
            memory: 4096

            # from 20 to 500 GB, this is for the main disk
            diskSize: 20

            # anything supported by the Anexia Engine, this is for the main disk
            diskPerformanceType: ENT6

            # specify additional disks here
            disks:
              - size: 200 # from 20 to 500 GB
                # anything supported by the Anexia Engine
                performanceType: ENT6

            # location ID from the Anexia Engine
            locationID: "<< ANEXIA_LOCATION_ID >>"

            # Each entry in this array will create a network interface in each
            # Machine, connected to the given VLAN.
            networks:
              - vlan: "<< ANEXIA_VLAN_ID >>"
                # (optional) BandwidthLimit, can be 100, 1000 or 10000 MBit/s or empty.
                bandwidthLimit: 1000

                # If prefixes are given, we reserve an IP address for each of
                # them - if you give one IPv4 and one IPv6 prefix, your
                # Machines will have dual-stack connectivity
                #
                # As an compatibility-aid for the old cloudProviderSpec.vlanID,
                # which reserved an IP for the configured VLAN, you can also
                # have an entry "" (empty string) to get the same behavior -
                # but this is not recommended.
                #
                # Not configuring any prefix might be useful if you want to
                # configure IP addresses on this interface via other means,
                # e.g. a Layer2 load balancer.
                #
                # Each MachineDeployment needs at least one Network with at
                # least one Prefix, because we have to know (and thus, reserve)
                # at least one IP address for each Machine.
                prefixes:
                  - "<< ANEXIA_PREFIX_ID >>"

            # Currently only the "Flatcar Linux Stable UEFI" template is supported.
            template: Flatcar Linux Stable UEFI
          # flatcar is the only supported operating system right now
          operatingSystem: flatcar
          operatingSystemSpec:
            disableAutoUpdate: false
            disableLocksmithD: true
            disableUpdateEngine: false
            # Force cloud-init instead of ignition. Anexia supports cloud-init only.
            provisioningUtility: cloud-init
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
      versions:
        kubelet: 1.35.0

